--## SQL 연습문제 (197p)
--홀수문제

CREATE TABLE STUDENT1
AS SELECT * 
FROM STUDENT 
WHERE STU_GRADE IN (1,2);

CREATE TABLE SUBJECT1
AS SELECT *
FROM SUBJECT;

CREATE TABLE ENROL1
AS SELECT *
FROM ENROL;

SELECT * FROM STUDENT1;
--Q1
INSERT INTO STUDENT1
VALUES(20101059, '조병준', '컴퓨터정보', 1, 'B', 'M', 164, 70);

SELECT * 
FROM STUDENT1;
--Q3
INSERT INTO STUDENT1
VALUES(20103009, '박소신', '기계', 
(SELECT STU_GRADE FROM STUDENT1 WHERE STU_NO = 20153075), 
(SELECT STU_CLASS FROM STUDENT1 WHERE STU_NO = 20153075), 
'M', NULL, NULL);

SELECT * 
FROM STUDENT1;
--Q5
UPDATE STUDENT1
SET STU_CLASS = 'B'
WHERE STU_NO = '20071001';

SELECT * 
FROM STUDENT1;
--Q7
UPDATE STUDENT1
SET STU_GRADE = STU_GRADE + 1;

SELECT * 
FROM STUDENT1;
--Q9
UPDATE ENROL1
SET ENR_GRADE = ENR_GRADE + 10
WHERE SUB_NO = (SELECT SUB_NO
FROM SUBJECT1
WHERE SUB_NAME = '전자회로실험');

SELECT * 
FROM ENROL1;
--Q11
DELETE FROM STUDENT1
WHERE STU_NO = 20093088;

SELECT * 
FROM STUDENT1;
--Q13
UPDATE SUBJECT1
SET SUB_NO = 501
WHERE SUB_NO = 110;

SELECT * 
FROM SUBJECT1;
--Q15
UPDATE ENROL1
SET SUB_NO = 999
WHERE SUB_NO NOT IN (SELECT SUB_NO
FROM SUBJECT1);

SELECT * 
FROM ENROL1;
--Q17
DELETE FROM ENROL1
WHERE SUB_NO = 999;

SELECT * 
FROM ENROL1;
--Q19
DELETE FROM SUBJECT1
WHERE SUB_NO NOT IN (SELECT SUB_NO
FROM ENROL1);

COMMIT;